# This is a generated file. Not intended for manual editing.
services:
  clinica.api.rest:
    build:
      context: "/Users/davidsalukvadze/Desktop/4Create/4Create"
      dockerfile: "src/Clinica.Api.Rest/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "clinica.api.rest:dev"
    ports:
    - "127.0.0.1:57001:57100"
    - "127.0.0.1:57201:57300"
    volumes:
    - "/Users/davidsalukvadze/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/davidsalukvadze/Desktop/4Create/4Create/src/Clinica.Api.Rest:/app:rw"
    - "/Users/davidsalukvadze/Desktop/4Create/4Create:/src:rw"
    - "/Users/davidsalukvadze/.local/share/JetBrains/RiderRemoteDebugger/2024.1.4/LinuxArm64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/davidsalukvadze/Library/Logs/JetBrains/Rider2024.1/DebuggerWorker/JetBrains.Debugger.Worker.2024_12_19_16_33_42:/var/opt/rider-debugger:rw"
    working_dir: "/app"
